# Generated by Django 6.0.2 on 2026-06-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('candidates', '0003_candidateprofile_career_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteractionlog',
            name='details',
            field=models.JSONField(blank=True, help_text='Store additional context like status names or job titles', null=True),
        ),
        migrations.AlterField(
            model_name='recruiteractionlog',
            name='action_type',
            field=models.CharField(choices=[('view', 'Viewed Profile'), ('shortlist', 'Shortlisted'), ('reject', 'Rejected'), ('save', 'Saved/Bookmarked'), ('status_change', 'Changed Application Status'), ('job_create', 'Created Job'), ('job_delete', 'Deleted Job'), ('talent_pool', 'Added to Talent Pool'), ('settings_update', 'Updated Settings')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiteractionlog',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_actions', to='candidates.candidateprofile'),
        ),
    ]
