from django.db.models import Count, Q, F, FloatField, ExpressionWrapper
from django.utils import timezone
from datetime import timedelta
from apps.candidates.models import CandidateProfile
from apps.analytics.models import RecruiterActionLog

def get_organic_ranking_queryset():
    """
    Returns a CandidateProfile queryset annotated with an `organic_score`
    based on profile completeness and platform-wide popularity (Marketplace Learning Loop).
    """
    thirty_days_ago = timezone.now() - timedelta(days=30)
    
    return CandidateProfile.objects.filter(is_open_to_work=True).annotate(
        # Base score from completeness (0-100)
        base_score=F('profile_completion'),
        
        # Bonus for being shortlisted recently
        shortlist_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.SHORTLIST,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Penalty for being rejected
        reject_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.REJECT,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Final calculated score
        organic_score=ExpressionWrapper(
            F('base_score') + (F('shortlist_count') * 5.0) - (F('reject_count') * 3.0),
            output_field=FloatField()
        )
    ).order_by('-organic_score')

def get_job_match_ranking_queryset(job_id):
    """
    Returns a CandidateProfile queryset annotated with `match_score` from a specific job.
    This requires that MatchScore records exist (e.g. generated by the matching service).
    """
    return CandidateProfile.objects.filter(
        is_open_to_work=True,
        matches__job_id=job_id
    ).annotate(
        match_score=F('matches__overall_score')
    ).order_by('-match_score')

def generate_relevance_data(candidate, job_id=None):
    """Generates the AI Insight data for a candidate, prioritizing Job Context if provided."""
    
    if job_id:
        # Job Context Matching
        from apps.matching.models import MatchScore
        match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
        
        # If match record doesn't exist yet, generate it on the fly
        if not match_record:
            from apps.jobs.models import Job
            from apps.matching.engine import compute_match
            job = Job.objects.filter(id=job_id).first()
            if job:
                match_data = compute_match(candidate, job)
                match_record, _ = MatchScore.objects.update_or_create(
                    job=job,
                    candidate=candidate,
                    defaults=match_data,
                )

        if match_record:
            breakdown = match_record.breakdown
            score = match_record.overall_score
            
            # Extract skills from TF-IDF/Fuzzy engine breakdown
            skills_data = breakdown.get('skills', {})
            matched = skills_data.get('matched', [])
            missing = skills_data.get('missing', [])
            
            exp_data = breakdown.get('experience', {})
            semantic_alignment = exp_data.get('semantic_alignment', 0)
            
            relevance_factors = [f"Semantic match: {semantic_alignment}%"] + [f"Has: {m}" for m in matched[:3]]
            missing_factors = [f"Missing: {m}" for m in missing[:3]]
            
            reason = f"This candidate matches your job with a Semantic Score of {score}%. "
            if matched:
                reason += f"Strong alignment in {', '.join(matched[:3])}. "
            if missing:
                reason += f"However, they may lack {', '.join(missing[:2])}."
                
            return {
                "ranking_score": score,
                "relevance_factors": relevance_factors,
                "missing_factors": missing_factors,
                "match_reason": reason
            }

    # Fallback to Organic Learning Loop
    score = getattr(candidate, 'organic_score', candidate.profile_completion)
    shortlists = getattr(candidate, 'shortlist_count', 0)
    
    factors = []
    if candidate.profile_completion > 80:
        factors.append("Highly complete profile")
    if candidate.years_of_experience >= 5:
        factors.append("Senior-level experience")
    if shortlists > 0:
        factors.append(f"Shortlisted by {shortlists} recruiters recently")
        
    reason = f"This candidate has an organic rank score of {score:.1f}. "
    if factors:
        reason += "They stand out due to: " + ", ".join(factors).lower() + "."
    else:
        reason += "They are actively open to work and matching your basic criteria."
        
    return {
        "ranking_score": score,
        "relevance_factors": factors,
        "missing_factors": [],
        "match_reason": reason
    }


def generate_outreach_draft(candidate, job_id, recruiter_user=None):
    """Generates a personalized outreach message based on Semantic Match context."""
    recruiter_name = "Recruiter"
    company_name_str = ""
    
    if recruiter_user:
        if recruiter_user.first_name:
            recruiter_name = f"{recruiter_user.first_name} {recruiter_user.last_name}".strip()
        
        if hasattr(recruiter_user, 'recruiter_profile') and recruiter_user.recruiter_profile.company:
            company_name_str = f"\n{recruiter_user.recruiter_profile.company.name}"
            
    sign_off = f"Best regards,\n{recruiter_name}{company_name_str}"

    if not job_id:
        return {"subject": "Opportunities at our company", "body": f"Hi {candidate.user.first_name},\n\nI came across your profile and was impressed by your background. We are currently hiring and I'd love to chat.\n\n{sign_off}"}
        
    from apps.matching.models import MatchScore
    from apps.jobs.models import Job
    job = Job.objects.filter(id=job_id).first()
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    
    if not job or not match_record:
        return {"subject": f"Opportunity: {job.title if job else 'Open Role'}", "body": f"Hi {candidate.user.first_name},\n\nI was impressed by your profile and would love to discuss a role we have open.\n\n{sign_off}"}

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    missing_skills = skills_bd.get('missing', []) if isinstance(skills_bd, dict) else []
    score = match_record.overall_score
    
    subject = f"Opportunity: {job.title} - Your background in {matched_skills[0] if matched_skills else 'tech'}"
    
    body = f"Hi {candidate.user.first_name},\n\n"
    body += f"I'm reaching out because your profile indicates a strong semantic alignment ({score:.0f}% match) with a {job.title} role I'm currently recruiting for at {job.company.name}.\n\n"
    
    if matched_skills:
        body += f"Specifically, your experience with {', '.join(matched_skills[:3])} stood out to me as highly relevant to our stack.\n\n"
        
    if missing_skills:
        body += f"While this role also touches on {', '.join(missing_skills[:2])}, our team is highly supportive and we're willing to help the right candidate ramp up in those areas.\n\n"
        
    body += "Are you open to a brief 10-minute chat this week to discuss further?\n\n"
    body += sign_off
    
    return {"subject": subject, "body": body}


def generate_interview_questions(candidate, job_id):
    """Generates tailored interview questions based on candidate's missing/matched skills."""
    if not job_id:
        return ["Can you walk me through your resume?", "What are your greatest strengths?", "Describe a challenge you overcame."]
        
    from apps.matching.models import MatchScore
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    
    if not match_record:
        return ["Can you walk me through your resume?", "What are your greatest strengths?", "Describe a challenge you overcame."]

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    missing_skills = skills_bd.get('missing', []) if isinstance(skills_bd, dict) else []
    
    questions = []
    
    if matched_skills:
        # Deep dive into a matched skill
        questions.append(f"You have experience with {matched_skills[0]}. Can you describe the most complex problem you've solved using this technology?")
        
    if len(matched_skills) > 1:
        questions.append(f"How do you typically structure your workflows when working with {matched_skills[1]}?")
        
    if missing_skills:
        # Probe missing skills
        questions.append(f"This role requires some familiarity with {missing_skills[0]}. Have you had any exposure to it, and how would you approach learning it quickly?")
        
    if len(missing_skills) > 1:
        questions.append(f"We also use {missing_skills[1]}. Since you don't have direct experience with it, what similar tools have you used that might translate well?")
        
    # Standard fallback if not enough skills to generate 4 questions
    while len(questions) < 4:
        fallbacks = [
            "Tell me about a time you had to learn a new framework on the fly.",
            "How do you handle technical disagreements within your team?",
            "What architectural decisions are you most proud of in your past roles?"
        ]
        for f in fallbacks:
            if f not in questions:
                questions.append(f)
                break
                
    return questions[:4]
