from django.db.models import Count, Q, F, FloatField, ExpressionWrapper
from django.utils import timezone
from datetime import timedelta
from apps.candidates.models import CandidateProfile
from apps.analytics.models import RecruiterActionLog

def get_organic_ranking_queryset():
    """
    Returns a CandidateProfile queryset annotated with an `organic_score`
    based on profile completeness and platform-wide popularity (Marketplace Learning Loop).
    """
    thirty_days_ago = timezone.now() - timedelta(days=30)
    
    return CandidateProfile.objects.filter(is_open_to_work=True).annotate(
        # Base score from completeness (0-100)
        base_score=F('profile_completion'),
        
        # Bonus for being shortlisted recently
        shortlist_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.SHORTLIST,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Penalty for being rejected
        reject_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.REJECT,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Final calculated score
        organic_score=ExpressionWrapper(
            F('base_score') + (F('shortlist_count') * 5.0) - (F('reject_count') * 3.0),
            output_field=FloatField()
        )
    ).order_by('-organic_score')

def get_job_match_ranking_queryset(job_id):
    """
    Returns a CandidateProfile queryset annotated with `match_score` from a specific job.
    This requires that MatchScore records exist (e.g. generated by the matching service).
    """
    return CandidateProfile.objects.filter(
        is_open_to_work=True,
        matches__job_id=job_id
    ).annotate(
        match_score=F('matches__overall_score')
    ).order_by('-match_score')

def generate_relevance_data(candidate, job_id=None):
    """Generates the AI Insight data for a candidate, prioritizing Job Context if provided."""
    
    if job_id:
        # Job Context Matching
        from apps.matching.models import MatchScore
        match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
        
        # If match record doesn't exist yet, generate it on the fly
        if not match_record:
            from apps.jobs.models import Job
            from apps.matching.engine import compute_match
            job = Job.objects.filter(id=job_id).first()
            if job:
                match_data = compute_match(candidate, job)
                match_record, _ = MatchScore.objects.update_or_create(
                    job=job,
                    candidate=candidate,
                    defaults=match_data,
                )

        if match_record:
            breakdown = match_record.breakdown
            score = match_record.overall_score
            
            # Extract skills from TF-IDF/Fuzzy engine breakdown
            skills_data = breakdown.get('skills', {})
            matched = skills_data.get('matched', [])
            missing = skills_data.get('missing', [])
            
            exp_data = breakdown.get('experience', {})
            semantic_alignment = exp_data.get('semantic_alignment', 0)
            
            relevance_factors = [f"Semantic match: {semantic_alignment}%"] + [f"Has: {m}" for m in matched[:3]]
            missing_factors = [f"Missing: {m}" for m in missing[:3]]
            
            reason = f"This candidate matches your job with a Semantic Score of {score}%. "
            if matched:
                reason += f"Strong alignment in {', '.join(matched[:3])}. "
            if missing:
                reason += f"However, they may lack {', '.join(missing[:2])}."
                
            return {
                "ranking_score": score,
                "relevance_factors": relevance_factors,
                "missing_factors": missing_factors,
                "match_reason": reason
            }

    # Fallback to Organic Learning Loop
    score = getattr(candidate, 'organic_score', candidate.profile_completion)
    shortlists = getattr(candidate, 'shortlist_count', 0)
    
    factors = []
    if candidate.profile_completion > 80:
        factors.append("Highly complete profile")
    if candidate.years_of_experience >= 5:
        factors.append("Senior-level experience")
    if shortlists > 0:
        factors.append(f"Shortlisted by {shortlists} recruiters recently")
        
    reason = f"This candidate has an organic rank score of {score:.1f}. "
    if factors:
        reason += "They stand out due to: " + ", ".join(factors).lower() + "."
    else:
        reason += "They are actively open to work and matching your basic criteria."
        
    return {
        "ranking_score": score,
        "relevance_factors": factors,
        "missing_factors": [],
        "match_reason": reason
    }
