from django.db.models import Count, Q, F, FloatField, ExpressionWrapper
from django.utils import timezone
from datetime import timedelta
from apps.candidates.models import CandidateProfile
from apps.analytics.models import RecruiterActionLog

def get_organic_ranking_queryset():
    """
    Returns a CandidateProfile queryset annotated with an `organic_score`
    based on profile completeness and platform-wide popularity (Marketplace Learning Loop).
    """
    thirty_days_ago = timezone.now() - timedelta(days=30)
    
    return CandidateProfile.objects.filter(is_open_to_work=True).annotate(
        # Base score from completeness (0-100)
        base_score=F('profile_completion'),
        
        # Bonus for being shortlisted recently
        shortlist_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.SHORTLIST,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Penalty for being rejected
        reject_count=Count('recruiter_actions', filter=Q(
            recruiter_actions__action_type=RecruiterActionLog.ActionType.REJECT,
            recruiter_actions__timestamp__gte=thirty_days_ago
        )),
        
        # Final calculated score
        organic_score=ExpressionWrapper(
            F('base_score') + (F('shortlist_count') * 5.0) - (F('reject_count') * 3.0),
            output_field=FloatField()
        )
    ).order_by('-organic_score')

def get_job_match_ranking_queryset(job_id):
    """
    Returns a CandidateProfile queryset annotated with `match_score` from a specific job.
    This requires that MatchScore records exist (e.g. generated by the matching service).
    """
    return CandidateProfile.objects.filter(
        is_open_to_work=True,
        matches__job_id=job_id
    ).annotate(
        match_score=F('matches__overall_score')
    ).order_by('-match_score')

def generate_relevance_data(candidate, job_id=None):
    """Generates the AI Insight data for a candidate, prioritizing Job Context if provided."""
    
    if job_id:
        # Job Context Matching
        from apps.matching.models import MatchScore
        match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
        
        # If match record doesn't exist yet, generate it on the fly
        if not match_record:
            from apps.jobs.models import Job
            from apps.matching.engine import compute_match
            job = Job.objects.filter(id=job_id).first()
            if job:
                match_data = compute_match(candidate, job)
                match_record, _ = MatchScore.objects.update_or_create(
                    job=job,
                    candidate=candidate,
                    defaults=match_data,
                )

        if match_record:
            breakdown = match_record.breakdown
            score = match_record.overall_score
            
            # Extract skills from TF-IDF/Fuzzy engine breakdown
            skills_data = breakdown.get('skills', {})
            matched = skills_data.get('matched', [])
            missing = skills_data.get('missing', [])
            
            exp_data = breakdown.get('experience', {})
            semantic_alignment = exp_data.get('semantic_alignment', 0)
            
            relevance_factors = [f"Semantic match: {semantic_alignment}%"] + [f"Has: {m}" for m in matched[:3]]
            missing_factors = [f"Missing: {m}" for m in missing[:3]]
            
            reason = f"This candidate matches your job with a Semantic Score of {score}%. "
            if matched:
                reason += f"Strong alignment in {', '.join(matched[:3])}. "
            if missing:
                reason += f"However, they may lack {', '.join(missing[:2])}."
                
            return {
                "ranking_score": score,
                "relevance_factors": relevance_factors,
                "missing_factors": missing_factors,
                "match_reason": reason
            }

    # Fallback to Organic Learning Loop
    score = getattr(candidate, 'organic_score', candidate.profile_completion)
    shortlists = getattr(candidate, 'shortlist_count', 0)
    
    factors = []
    if candidate.profile_completion > 80:
        factors.append("Highly complete profile")
    if candidate.years_of_experience >= 5:
        factors.append("Senior-level experience")
    if shortlists > 0:
        factors.append(f"Shortlisted by {shortlists} recruiters recently")
        
    reason = f"This candidate has an organic rank score of {score:.1f}. "
    if factors:
        reason += "They stand out due to: " + ", ".join(factors).lower() + "."
    else:
        reason += "They are actively open to work and matching your basic criteria."
        
    return {
        "ranking_score": score,
        "relevance_factors": factors,
        "missing_factors": [],
        "match_reason": reason
    }


def generate_outreach_draft(candidate, job_id, recruiter_user=None):
    """Generates a personalized outreach message based on Semantic Match context."""
    from apps.core.llm import generate_text
    
    recruiter_name = "Recruiter"
    company_name_str = ""
    
    if recruiter_user:
        if recruiter_user.first_name:
            recruiter_name = f"{recruiter_user.first_name} {recruiter_user.last_name}".strip()
        
        if hasattr(recruiter_user, 'recruiter_profile') and recruiter_user.recruiter_profile.company:
            company_name_str = f"\n{recruiter_user.recruiter_profile.company.name}"
            
    sign_off = f"Best regards,\n{recruiter_name}{company_name_str}"

    if not job_id:
        return {"subject": "Opportunities at our company", "body": f"Hi {candidate.user.first_name},\n\nI came across your profile and was impressed by your background. We are currently hiring and I'd love to chat.\n\n{sign_off}"}
        
    from apps.matching.models import MatchScore
    from apps.jobs.models import Job
    job = Job.objects.filter(id=job_id).first()
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    
    if not job or not match_record:
        return {"subject": f"Opportunity: {job.title if job else 'Open Role'}", "body": f"Hi {candidate.user.first_name},\n\nI was impressed by your profile and would love to discuss a role we have open.\n\n{sign_off}"}

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    
    subject = f"Opportunity: {job.title} - Your background in {matched_skills[0] if matched_skills else 'tech'}"
    
    prompt = f"""
Act as a professional technical recruiter. Write a highly personalized, compelling, and concise outreach email (2-3 short paragraphs) to a candidate named {candidate.user.first_name}.

Context:
- You are recruiting for a "{job.title}" role at "{job.company.name}".
- The candidate has these relevant skills that match the job: {', '.join(matched_skills[:5]) if matched_skills else 'a strong background in tech'}.
- The match score was {match_record.overall_score:.0f}%, meaning they are a great fit.

Goal:
- Highlight why their specific background caught your eye.
- Mention the job title and company.
- Ask for a brief 10-minute chat this week.
- Do NOT include a subject line in the text, just the body.
- End the email exactly with this sign-off (do not change it or add placeholders):

{sign_off}
"""
    
    body = generate_text(prompt, temperature=0.7).strip()
    
    return {"subject": subject, "body": body}

def generate_outreach_draft_stream(candidate, job_id, recruiter_user=None):
    """Generates a personalized outreach message stream based on Semantic Match context."""
    from apps.core.llm import generate_text_stream
    from apps.matching.models import MatchScore
    from apps.jobs.models import Job
    
    recruiter_name = "Recruiter"
    company_name_str = ""
    
    if recruiter_user:
        if recruiter_user.first_name:
            recruiter_name = f"{recruiter_user.first_name} {recruiter_user.last_name}".strip()
        
        if hasattr(recruiter_user, 'recruiter_profile') and recruiter_user.recruiter_profile.company:
            company_name_str = f"\n{recruiter_user.recruiter_profile.company.name}"
            
    sign_off = f"Best regards,\n{recruiter_name}{company_name_str}"

    if not job_id:
        yield f"Hi {candidate.user.first_name},\n\nI came across your profile and was impressed by your background. We are currently hiring and I'd love to chat.\n\n{sign_off}"
        return
        
    job = Job.objects.filter(id=job_id).first()
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    
    if not job or not match_record:
        yield f"Hi {candidate.user.first_name},\n\nI was impressed by your profile and would love to discuss a role we have open.\n\n{sign_off}"
        return

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    
    prompt = f"""
Act as a professional technical recruiter. Write a highly personalized, compelling, and concise outreach email (2-3 short paragraphs) to a candidate named {candidate.user.first_name}.

Context:
- You are recruiting for a "{job.title}" role at "{job.company.name}".
- The candidate has these relevant skills that match the job: {', '.join(matched_skills[:5]) if matched_skills else 'a strong background in tech'}.
- The match score was {match_record.overall_score:.0f}%, meaning they are a great fit.

Goal:
- Highlight why their specific background caught your eye.
- Mention the job title and company.
- Ask for a brief 10-minute chat this week.
- Do NOT include a subject line in the text, just the body.
- End the email exactly with this sign-off (do not change it or add placeholders):

{sign_off}
"""
    
    yield from generate_text_stream(prompt, temperature=0.7)


def generate_interview_questions(candidate, job_id):
    """Generates tailored interview questions using Gemini."""
    if not job_id:
        return ["Can you walk me through your resume?", "What are your greatest strengths?", "Describe a challenge you overcame."]
        
    from apps.matching.models import MatchScore
    from apps.jobs.models import Job
    from apps.core.llm import generate_text
    
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    job = Job.objects.filter(id=job_id).first()
    
    if not match_record or not job:
        return ["Can you walk me through your resume?", "What are your greatest strengths?", "Describe a challenge you overcame."]

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    missing_skills = skills_bd.get('missing', []) if isinstance(skills_bd, dict) else []
    
    prompt = f"""
Act as a senior hiring manager preparing for an interview for a "{job.title}" role.

Candidate Context:
- They already possess these required skills: {', '.join(matched_skills) if matched_skills else 'general industry skills'}.
- They are missing or weak in these required skills: {', '.join(missing_skills) if missing_skills else 'no major skill gaps'}.

Task:
Generate exactly 4 highly specific and insightful interview questions to ask this candidate.
- 2 questions should dive deep into their existing skills to verify their expertise.
- 2 questions should probe their ability to learn or handle the missing skills.

Output Format:
Return ONLY a numbered list of the 4 questions. No introductions, no explanations, no markdown other than numbers (1. 2. 3. 4.).
"""
    
    text = generate_text(prompt, temperature=0.7)
    
    questions = []
    for line in text.split('\n'):
        line = line.strip()
        if line and line[0].isdigit() and (line[1] == '.' or line[1] == ')'):
            questions.append(line.split(' ', 1)[-1].strip())
            
    if len(questions) < 4:
        fallbacks = [
            "Tell me about a time you had to learn a new technology on the fly.",
            "How do you handle technical disagreements within your team?",
            "What architectural decisions are you most proud of in your past roles?",
            "Can you walk me through your most complex project?"
        ]
        for f in fallbacks:
            if len(questions) < 4:
                questions.append(f)
                
    return questions[:4]

def generate_interview_questions_stream(candidate, job_id):
    """Generates tailored interview questions stream using Gemini."""
    if not job_id:
        yield "1. Can you walk me through your resume?\n2. What are your greatest strengths?\n3. Describe a challenge you overcame."
        return
        
    from apps.matching.models import MatchScore
    from apps.jobs.models import Job
    from apps.core.llm import generate_text_stream
    
    match_record = MatchScore.objects.filter(candidate=candidate, job_id=job_id).first()
    job = Job.objects.filter(id=job_id).first()
    
    if not match_record or not job:
        yield "1. Can you walk me through your resume?\n2. What are your greatest strengths?\n3. Describe a challenge you overcame."
        return

    breakdown = match_record.breakdown or {}
    skills_bd = breakdown.get('skills', {}) if isinstance(breakdown, dict) else {}
    matched_skills = skills_bd.get('matched', []) if isinstance(skills_bd, dict) else []
    missing_skills = skills_bd.get('missing', []) if isinstance(skills_bd, dict) else []
    
    prompt = f"""
Act as a senior hiring manager preparing for an interview for a "{job.title}" role.

Candidate Context:
- They already possess these required skills: {', '.join(matched_skills) if matched_skills else 'general industry skills'}.
- They are missing or weak in these required skills: {', '.join(missing_skills) if missing_skills else 'no major skill gaps'}.

Task:
Generate exactly 4 highly specific and insightful interview questions to ask this candidate.
- 2 questions should dive deep into their existing skills to verify their expertise.
- 2 questions should probe their ability to learn or handle the missing skills.

Output Format:
Return ONLY a numbered list of the 4 questions. No introductions, no explanations, no markdown other than numbers (1. 2. 3. 4.).
"""
    
    yield from generate_text_stream(prompt, temperature=0.7)
