# Generated by Django 6.0.2 on 2026-06-05 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the category listing page.')),
                ('color', models.CharField(default='blue', help_text='Tailwind colour name (blue, green, purple, rose, amber, teal).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Main article headline (H1).', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short teaser shown on listing page (150–160 chars ideal for SEO).', max_length=300)),
                ('content', models.TextField(help_text='Full article body. Supports HTML / Markdown from the editor.')),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended size: 1200×630 px (OpenGraph standard).', null=True, upload_to='blog/covers/')),
                ('cover_image_alt', models.CharField(blank=True, help_text='Alt text for cover image - important for accessibility & image SEO.', max_length=200)),
                ('seo_title', models.CharField(blank=True, help_text='Override the <title> tag (ideal: 50–60 chars). Leave blank to use main title.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description (ideal: 120–155 chars). Shown in Google search results.', max_length=160)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords. Not used by Google but useful for internal tracking.', max_length=300)),
                ('canonical_url', models.URLField(blank=True, help_text='Optional: Set if this content is syndicated from another URL.')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing (overrides cover_image if set).', null=True, upload_to='blog/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Featured / Hero section.')),
                ('allow_comments', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Platform admin who wrote this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
