# Generated by Django 6.0.2 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Company Subscription', 'verbose_name_plural': 'Company Subscriptions'},
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('paused', 'Paused')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
