# Generated by Django 6.0.5 on 2026-06-01 20:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employment_type_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
