# Generated by Django 6.0.5 on 2026-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_banners/'),
        ),
    ]
