# Generated by Django 6.0.2 on 2026-06-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_career_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateskill',
            name='is_verified_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=50),
        ),
    ]
