# Generated by Django 6.0.2 on 2026-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_department_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_headhunt',
            field=models.BooleanField(default=True),
        ),
    ]
