# Generated by Django 6.0.5 on 2026-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
    ]
