# Generated by Django 6.0.2 on 2026-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_talentpool_talentpoolmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
