# Generated by Django 6.0.2 on 2026-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_recruiterprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='company',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
